language: bash
install:
  - git symbolic-ref --short HEAD || git checkout ${TRAVIS_BRANCH}
script:
  - ./bs docker --buildNum=${TRAVIS_BUILD_NUMBER}
  - docker login docker.pkg.github.com -u ${GH_DOCKER_USER} -p ${GH_DOCKER_PW}
  - 'if [ "$TRAVIS_PULL_REQUEST"  = "false" ]; then ./bs dockerPush; fi'
