---
server:
  port: 8002
  serverUrl: ''
  clientUrl: ''
  trustProxy: loopback
db:
  url: mongodb://localhost:27018
  name: skidb
  user: ''
  password: ''
  collections:
    areas:
      indexes:
      - key:
          name: 1
      - key:
          resort: 1
      - key:
          timestamp: -1
    lifts:
      indexes:
      - key:
          name: 1
      - key:
          resort: 1
      - key:
          timestamp: -1
    runs:
      indexes:
      - key:
          name: 1
      - key:
          resort: 1
      - key:
          timestamp: -1
    weather:
      indexes:
      - key:
          resort: 1
      - key:
          timestamp: -1
scraper:
  enabled: true
  cron:
    interval: 0 */15 * * * * # every 15 minutes
